indentation_width: 4
cyclomatic_complexity:
  warning: 6
  error: 7
file_length:
  error: 1000
function_body_length: 
  warning: 35
function_parameter_count: 4
line_length:
  error: 150
type_body_length: 300
variable_name:
  min_length:
    error: 1
  excluded:
    - N

disabled_rules:
  - valid_docs
  - identifier_name

line_length:
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

force_cast: warning
force_try:
  severity: error
  
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - JobFinderAppTests
  - JobFinderAppUITests

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html)
